# Generated by Django 5.2.6 on 2025-09-11 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUGreenApp', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiusagelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_logs', to=settings.AUTH_USER_MODEL),
        ),
    ]
