# Generated by Django 5.2.6 on 2025-09-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUGreenApp', '0004_newslettersubscriber'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='news',
            name='OUGreenApp__title_a11468_idx',
        ),
        migrations.RemoveIndex(
            model_name='news',
            name='OUGreenApp__created_fa5ce3_idx',
        ),
        migrations.AddField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=20),
        ),
    ]
