# Generated by Django 5.2.6 on 2025-09-11 16:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OUGreenApp', '0005_remove_news_ougreenapp__title_a11468_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcontest',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='ProjectContest/'),
        ),
    ]
