# Generated by Django 5.2.6 on 2025-09-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OUGreenApp', '0006_projectcontest_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='OUGreenApp.category'),
        ),
    ]
